# Generated by Django 4.1.7 on 2023-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StartTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeRange',
        ),
    ]
